### ISSUE TITLE
해당 달에 일기 존재하는 날짜 조회 api (/calendar) 예외 처리 요청

### ISSUE THREAD

**Issue by 0703kyj** [Konkuk-ThanksD/Server#13]
- 제가 저번 코드 리뷰에서 놓친 것 같은데 예외처리가 안되어 있는 것 같아요..!  

### 1. year : 20232, month: 12
![image](https://github.com/Konkuk-ThanksD/Server/assets/127181370/4bf433c5-4029-4845-b24a-59d8ca999ba3)
200으로 오는데 이렇게 의도하신게 맞으신가요?

### 2. year:2023, month: 13
![image](https://github.com/Konkuk-ThanksD/Server/assets/127181370/1e1032cc-9801-4ff3-b31a-2d99b8e2a796)
이렇게 응답이 옵니다..!
콘솔엔
![image](https://github.com/Konkuk-ThanksD/Server/assets/127181370/d44ae4ab-0773-4471-92ae-a21d7f420b20)
이렇게 찍힙니다!

**Comment by Ji-soo708** [comment]
아 넵넵 해당 기능은 #12 와 달리 파람을 받을 때 int로만 받는데 그래서 내부 로직에서 파싱같은 작업이 이루어지지 않습니다. 그런데 영준님 말씀대로 유효한 달인지 체크를 해주는 검증 로직이 들어가는 게 좋을 거 같아서 저녁에 처리하겠습니다! 감사합니다~
